dlemstra/Magick.NET

- Magick.NET/Core/Profiles/Iptc/IptcProfile.cs
Allows to keep IPTC fields not specified in IptcTag enum.
> Fixed handling of unspecified IPTC fields

- Source/Magick.NET/Core/MagickImage.cs
I observed that a positive value for `degrees` rotate CS, and a negative value rotates CCW.
> fixes documentation for rotate function

- Source/Magick.NET/Shared/Profiles/Exif/ExifTag.cs
The On, Red-eye reduciton, Return Detected was set to 69 = 0x45. This is
actually: Flash fired, red-eye reduction mode, return light not detected.
> Fix Flash ExifTagDescription for 0x4F

- Documentation/CrossPlatform.md
It took me way longer than it should have to figure out the path that actually needed to be used here. Letting the user know which files `ImageMagick/libraries` is referring to is a simple change with a huge benefit.
> Update CrossPlatform.md - Clarify expected path

- .github/CONTRIBUTING.md
There were two 'follow' written. Corrected that! :)
> grammatical error in CONTRIBUTING.md

- Source/Magick.NET/Shared/Helpers/Throw.cs
In Throw.IfNullOrEmpty for Stream, separate the length check and the position check so that clearer feedback can be provided for both cases.
Fixes #321
> Make exception messages for stream validation more specific

- Source/Magick.NET/Shared/Optimizers/ImageOptimizer.cs
- Tests/Magick.NET.Tests/Shared/Optimizers/ImageOptimizerTests.cs
Add a `IgnoreUnsupportedFormats` option to ImageOptimizer, which when set to true causes the compression methods to return false (indicating compression failed) for unsupported files, instead of throwing an exception.
Fixes #269
> Add option to ImageOptimizer to skip compressing files in unsupported formats instead of throwing an exception

- Source/Magick.NET/Framework/MagickImage.cs
I work with scanned images. MagickImage loads right dencity of images. But when I convert them to bitmapsource, dencity changes to standard value - 96.
I made some changes to produce right dencity.
ToBitmapSource() method returns BitmapSource with right dencity of original image.
> Add Dencity to return value ToBitmapSource()

- src/Magick.NET/Shared/Defines/ProfileTypes.cs
- src/Magick.NET/Shared/Profiles/Iptc/IIptcProfile.cs
- src/Magick.NET/Shared/Profiles/Iptc/IptcProfile.cs
- src/Magick.NET/Shared/Profiles/Iptc/IptcTag.cs
- src/Magick.NET/Shared/Profiles/Iptc/IptcTagExtensions.cs
- tests/Magick.NET.Tests/Shared/Profiles/Iptc/IptcProfileTests.cs
The IPTC specification allows some values to be present more than once. This PR adds the possibility to add those values multiple times. This solves #262.
> Add the possibility to add some IPTC values with the same tag more than once

- docs/CrossPlatform.md
Fix missing end tag slash for <MagickCopyNative*> on documentation.
> Fix missing end tag slash

- docs/CombiningImages.md
- samples/Magick.NET.Samples/CombiningImages.cs
This pull request adds an example on how to use the GifDisposeMethod in the "Create animated gif" examples section.
The reason for adding this change to the documentation is to help those who are trying to figure out how to remove the overlapping effect being caused by frames stacking on top of each other (due to frames having transparency in this instance).
This change should help those who are trying to find a solution to the frame overlapping issue, but without being sent to ImageMagick documentation instead of Magick.NET documentation.
> Updated some documentation.

- Building.md
- src/Magick.NET.Core/Factories/IMagickGeometryFactory.cs
- src/Magick.NET.Core/IMagickImage{TQuantumType}.cs
- src/Magick.NET/Drawables/DrawablePopGraphicContext.cs
- src/Magick.NET/Factories/MagickGeometryFactory.cs
- src/Magick.NET/MagickImage.cs
- src/Magick.NET/Types/MagickGeometry.cs
> typo: fix some typos

- src/Magick.NET.Core/Enums/PixelMapping.cs
This adds BGRA to the PixelMapping enum for convenience
The specific use case is with `Microsoft.UI.Xaml.Media.Imaging.WriteableBitmap.PixelBuffer` which takes BGRA format.
Placed at the end of the enum to preserve existing values.
> Add BGRA to PixelMapping.cs

- src/Magick.NET.Core/Enums/AlphaOption.cs
This copies over the descriptions from the official docs.
I think adding the full descriptions here would be useful. Although it does present a potential source of maintenance if things change. 
Good or bad to update the xml comments like this in some places?
* Discrete has no documentation
* On/Off don't either, although they are somewhat self-explanatory
* Undefined has... undefined behavior
* Associate/Disassociate docs are somewhat ambiguous compared to the others
> Update AlphaOption.cs xml docs

- src/Magick.NET/Native/Settings/DrawingSettings.cs
:wave: 
According to `Magick.Native` source (https://github.com/dlemstra/Magick.Native/blob/8a7ebef5a388229e790cca7c6caa0d3bbc71e142/src/Magick.Native/Settings/DrawingSettings.h#L82), there is no exception for `DrawingSettings.SetAffine`.
Regards.
> native: remove out exception from DrawingSettings.SetAffine

- src/Magick.NET/Settings/MagickSettings.cs
:wave: 
Fix related to #1520.
Properties affected: 
- FontFamily
- FontStyle
- FontWeight
Regards.
> fix: magickSettings: use backing Drawing property instead of options

- src/Magick.NET/MagickImage.cs
- tests/Magick.NET.Tests/MagickImageTests/TheAdaptiveThresholdMethod.cs
:wave:
- [ImageMagick](https://github.com/ImageMagick/ImageMagick/blob/12b1e53ffcf6d4fddfb7222b981bb8324c9b9a97/MagickCore/threshold.c#L219) requires `size_t` for `with` & `height`, but allow 0.
- no checks done on https://github.com/dlemstra/Magick.Native/blob/a01f5e641d52b1bbf2bf6f5795aba4b4c054a22d/src/Magick.Native/MagickImage.c#L700-L711
- no checks done on binding, only casting https://github.com/dlemstra/Magick.NET/blob/dd30d8bf913d79e1b3b7e7f1ea113020ff823751/src/Magick.NET/Native/MagickImage.cs#L3933-L3958
Regards.
> fix: add guards for MagickImage.AdaptiveThreshold

- src/Magick.NET.Core/IMagickImage.cs
- src/Magick.NET/MagickImage.cs
- tests/Magick.NET.Tests/MagickImageTests/TheBilateralBlurMethod.cs
:wave:
* https://github.com/ImageMagick/ImageMagick/blob/0c0f0a4e832271a1a37b872e8b76c100e81945c2/MagickCore/effect.c#L896-L897 requires `size_t` for `witdh` & `height` ; some lines later, they are bounded to 1 at minimum
* no checks done on https://github.com/dlemstra/Magick.Native/blob/d0a63d7f3852652c7c5c68c1950a00de015878f5/src/Magick.Native/MagickImage.c#L823-L832
* no checks done on binding, except casting to UInt (so >= 0) https://github.com/dlemstra/Magick.NET/blob/6035129aa06e7033fb8f7e65a8f2206486ae27ff/src/Magick.NET/Native/MagickImage.cs#L4157-L4182
Same could be done for `intensitySigma` & `spatialSigma`, but ImageMagick always multiply each param by itself, making them always positive.
On one hand, it's already "safe".
On the other hand, there is nothing (at least comments) …
> fix: add guards for MagickImage.BilateralBlur

- src/Magick.NET.Core/IMagickImage.cs
- src/Magick.NET/MagickImage.cs
- tests/Magick.NET.Tests/MagickImageTests/TheClaheMethod.cs
:wave:
* https://github.com/ImageMagick/ImageMagick/blob/0c0f0a4e832271a1a37b872e8b76c100e81945c2/MagickCore/enhance.c#L616-L785 requires `size_t` for `witdh`, `height` & `number_bins`
* no checks done on https://github.com/dlemstra/Magick.Native/blob/cdf9e6080ac714c8497ffd600b4022a0b4464292/src/Magick.Native/MagickImage.c#L925-L930
* no checks done on binding, except casting to UInt (so >= 0) https://github.com/dlemstra/Magick.NET/blob/167add42cd0875318d6bea71a8ebc14d6bbbb305/src/Magick.NET/Native/MagickImage.cs#L4411-L4433
Regards.
Edit: can rebase and/or squash if necessary.
Edit2: rebased because of lasts commit fixing MacOS pipeline
> fix: add guards for MagickImage.Clahe

- src/Magick.NET/Colors/MagickColor.cs
Use Quantum.Convert for K value same as red, green, blue.
I don't find a "good reason" that would explain a simple casting without check. But I'm may be wrong;
Regards.
> Use Quantum.Convert for K value in MagickColor

- src/Magick.NET/Formats/Tiff/TiffReadDefines.cs
- tests/Magick.NET.Tests/Formats/Tiff/TiffReadDefinesTests/TheIgnoreExifPopertiesProperty.cs
:wave: 
Fixed a typo in `TiffReadDefines`: `IgnoreExifPoperties` -> `IgnoreExifProperties` ; since it's part of the public api, I kept the old one and make it Obsolete.
I guess it should go there https://github.com/dlemstra/Magick.NET/issues/1374.
Regards.
> typo: TiffReadDefines.IgnoreExifPoperties -> IgnoreExifProperties

- src/Magick.NET/MagickImage.cs
- tests/Magick.NET.Tests/MagickImageTests/TheLowerMethod.cs
:wave:
* https://github.com/ImageMagick/ImageMagick/blob/0deac72ed480ac2ec8e9d766c15ddb3bca055952/MagickCore/geometry.h#L129-L138 requires `size_t` for `width`, `height` ; struct used in https://github.com/ImageMagick/ImageMagick/blob/0deac72ed480ac2ec8e9d766c15ddb3bca055952/MagickCore/decorate.c#L628-L631
* https://github.com/dlemstra/Magick.Native/blob/4b111a550d57c4e7c95ba9bc486581c07981d9d4/src/Magick.Native/MagickImage.c#L1920-L1930 requires `size_t` for `size`
* no checks done on binding, except casting to UInt (so >= 0) https://github.com/dlemstra/Magick.NET/blob/f66b8aaf27a7e3d3f32fbf4605154f32573b1cd4/src/Magick.NET/Native/MagickImage.cs#L6829-L6851
Regards 🙂
> fix: add guards for MagickImage.Lower

- src/Magick.NET/MagickImage.cs
- tests/Magick.NET.Tests/Factories/MagickGeometryFactoryTests/TheCreateMethod.cs
- tests/Magick.NET.Tests/MagickImageTests/TheAdaptiveResizeMethod.cs
- tests/Magick.NET.Tests/MagickImageTests/TheChopMethod.cs
- tests/Magick.NET.Tests/MagickImageTests/TheCloneMethod.cs
- tests/Magick.NET.Tests/MagickImageTests/TheCropMethod.cs
- tests/Magick.NET.Tests/MagickImageTests/TheExtentMethod.cs
- tests/Magick.NET.Tests/MagickImageTests/TheFrameMethod.cs
- tests/Magick.NET.Tests/MagickImageTests/TheInterpolativeResizeMethod.cs
- tests/Magick.NET.Tests/MagickImageTests/TheLiquidRescaleMethod.cs
- tests/Magick.NET.Tests/MagickImageTests/TheResizeMethod.cs
- tests/Magick.NET.Tests/MagickImageTests/TheSampleMethod.cs
- tests/Magick.NET.Tests/MagickImageTests/TheScaleMethod.cs
- tests/Magick.NET.Tests/MagickImageTests/TheThumbnailMethod.cs
From https://github.com/dlemstra/Magick.NET/discussions/1568
- Remove redundant checks
- Add missing tests
Regards.
> opti: remove redundant tests before creating MagickGeometry

- src/Magick.NET.Core/Types/Percentage.cs
- src/Magick.NET/MagickImage.cs
- src/Magick.NET/ResourceLimits.cs
- src/Magick.NET/Types/MagickGeometry.cs
- src/Shared/Throw.cs
- tests/Magick.NET.Core.Tests/Types/PercentageTests/TheConstructor.cs
- tests/Magick.NET.Tests/Factories/MagickGeometryFactoryTests/TheCreateMethod.cs
- tests/Magick.NET.Tests/MagickImageTests/TheColorizeMethod.cs
- tests/Magick.NET.Tests/MagickImageTests/TheContrastStretchMethod.cs
- tests/Magick.NET.Tests/MagickImageTests/TheDeskewMethod.cs
- tests/Magick.NET.Tests/MagickImageTests/TheInterpolativeResizeMethod.cs
- tests/Magick.NET.Tests/MagickImageTests/TheLiquidRescaleMethod.cs
- tests/Magick.NET.Tests/MagickImageTests/TheRangeThresholdMethod.cs
- tests/Magick.NET.Tests/MagickImageTests/TheResizeMethod.cs
- tests/Magick.NET.Tests/MagickImageTests/TheSampleMethod.cs
- tests/Magick.NET.Tests/MagickImageTests/TheScaleMethod.cs
- tests/Magick.NET.Tests/MagickImageTests/TheThumbnailMethod.cs
- tests/Magick.NET.Tests/ResourceLimitsTests/TheLimitMemoryMethod.cs
:wave: 
As discussed https://github.com/dlemstra/Magick.NET/discussions/1568#discussioncomment-8635702, this PR make Percentage positive only (including zero).
Therefore:
- all guards checking if percentage value is negative has been removed
- all tests where `Percentage` was initialized with negative value has been removed
Regards.
> feat: make Percentage only positive

- src/Magick.NET/MagickImage.cs
- tests/Magick.NET.Tests/MagickImageTests/TheSetBitDepthMethod.cs
:wave:
* https://github.com/ImageMagick/ImageMagick/blob/0deac72ed480ac2ec8e9d766c15ddb3bca055952/MagickCore/attribute.h#L38 requires `size_t` for `depth`
* https://github.com/dlemstra/Magick.Native/blob/8861d8354cad042aa39e0daed47f70327cba03f5/src/Magick.Native/MagickImage.c#L2203-L2210 requires `size_t` for `value`
* no checks done on binding, except casting to UInt (so >= 0) https://github.com/dlemstra/Magick.NET/blob/e49ebfe1fc238bb985855ea5d4b9eae6c06eb646/src/Magick.NET/Native/MagickImage.cs#L7550-L7572
Regards 🙂
> fix: add guards for MagickImage.SetBitDepth

- src/Magick.NET/MagickImage.cs
- tests/Magick.NET.Tests/MagickImageTests/TheShaveMethod.cs
:wave:
Same as usual 😅 : adding guards to prevent negative parameters.
Regards.
> fix: add guards for MagickImage.Shave

- src/Magick.NET.Core/IMagickImageInfo.cs
- src/Magick.NET/MagickImageInfo.cs
- tests/Magick.NET.Tests/MagickImageInfoTests/TheReadCollectionMethod.cs
- tests/Magick.NET.Tests/MagickImageInfoTests/TheReadMethod.cs
Orientation is a useful piece of information to have about an image and can be added very simply / at no extra cost to IMagickImageInfo
This pull request adds an Orientation property to IMagickImageInfo/MagickImageInfo. The code follows the same pattern as the other properties on IMagickImageInfo.
> add orientation to MagickImageInfo

- src/Magick.NET.Core/IMagickImage.cs
- src/Magick.NET/MagickImage.cs
- tests/Magick.NET.Tests/MagickImageTests/TheMorphologyMethod.cs
:wave: 
I had to take a look at [ImageMagick source code](https://github.com/ImageMagick/ImageMagick/blob/80b7ad564764ee0a24994c4c2feabf145a3eeb89/MagickCore/morphology.c#L4118-L4121) to understand why `MagickImage.Morphology`'s `iterations` parameter can be negative.
So this PR add both a guard and update documentation for the parameter.
Regards.
> fix: add guard for MagickImage.Morphology

- src/Magick.NET.Core/Statistics/IMoments.cs
- src/Magick.NET.Core/Statistics/IPerceptualHash.cs
- src/Magick.NET/Statistics/Moments.cs
- src/Magick.NET/Statistics/PerceptualHash.cs
- tests/Magick.NET.Tests/Statistics/MomentsTests/TheGetChannelMethod.cs
- tests/Magick.NET.Tests/Statistics/PerceptualHashTests/TheGetChannelMethod.cs
- tests/Magick.NET.Tests/Statistics/PerceptualHashTests/TheSumSquaredDistanceMethod.cs
:wave: 
Theses method doesn't use the result of `TryGetValue` and expect a non-null result:
https://github.com/dlemstra/Magick.NET/blob/d58472f4ad2157fd9a649dea7464370dee6621ea/src/Magick.NET/Statistics/Moments.cs#L39-L43
https://github.com/dlemstra/Magick.NET/blob/d58472f4ad2157fd9a649dea7464370dee6621ea/src/Magick.NET/Statistics/PerceptualHash.cs#L66-L70
This one can - explicitly - return a null value:
https://github.com/dlemstra/Magick.NET/blob/d58472f4ad2157fd9a649dea7464370dee6621ea/src/Magick.NET/Statistics/Statistics.cs#L35-L39
This PR:
- remove the `TryGetValue` for the first too method and use index access
- tests are added accordingly
- documentation is not (yet) updated (don't know if it's necessary)
If otherwise you prefer to not change the actual behavior (as it might be a …
> perf: use index access to Dictionary

- src/Magick.NET.Core/IMagickImage.cs
- src/Magick.NET/MagickImage.cs
:wave: 
It's just a missing doc tag.
Regards.
> doc: missing Exception for MagickImage.OilPaint

- src/Magick.NET.Core/Statistics/IChannelPerceptualHash.cs
- src/Magick.NET.Core/Statistics/IPerceptualHash.cs
- src/Magick.NET/Statistics/ChannelPerceptualHash.cs
- src/Magick.NET/Statistics/PerceptualHash.cs
:wave:
Just a typo in `*PerceptualHash` classes summary.
> Remove typo in *PerceptualHash summaries.

- src/Magick.NET/MagickImage.cs
:wave:
This PR is a simple optimization for Resample method, avoiding creating a useless `PointD` object.
Regards.
> opti: don't create PointD for MagickImage.Resample

- src/Magick.NET.Core/IMagickImage.cs
:wave: 
This PR add one variant of ToBase64 to the interface. Implementation is already there, tests too.
Regards.
> fix: add missing interface declaration for IMagickImage.ToBase64

- src/Magick.NET/MagickImage.cs
:wave: 
It avoids looping + contains check.
Regards.
> opti: use a HashSet instead of List

- src/Magick.NET/Native/Drawables/DrawingWand.cs
:wave: 
According to Magick.Native and ImageMagick sources, the parameter `value` of NativeDrawingWand.FillColor cannot be null:
https://github.com/dlemstra/Magick.Native/blob/6db05942001f01c3f344aa39064fb2d6413e0e46/src/Magick.Native/Drawables/DrawingWand.c#L151-L157
https://github.com/ImageMagick/ImageMagick/blob/0deac72ed480ac2ec8e9d766c15ddb3bca055952/MagickWand/drawing-wand.c#L4783-L4794
> fix: NativeDrawingWand.FillColor value can't be null

- src/Magick.NET/Formats/Dds/DdsReadDefines.cs
- src/Magick.NET/Formats/Dng/DngReadDefines.cs
- src/Magick.NET/Formats/Pdf/PdfWriteDefines.cs
- src/Magick.NET/Formats/WebP/WebPWriteDefines.cs
- changing 'wether' to 'whether'
- changing 'whitebalance' to 'white balance'
This pull request corrects some minor spelling mistakes in the XML documentation comments
> Fix typos in XML documentation comments

- src/Magick.NET.SystemDrawing/ImageFormatExtensions.cs
When working with serialized images, e.g. embedded resources in WinForms, the equality check of the extension method fails. When deserializing the image, a new instance of `ImageFormat` is created, which still uses the same `Guid` as the singleton instance, but represents a whole new instance, thus failing the equality check.
> Fix ImageFormat equality comparison

- src/Magick.NET.Core/IMagickImage{TQuantumType}.cs
Renaming param to fit the implementation.
> typo: IMagickImage.InverseLevel rename midpoint to gamma

- docs/LosslessCompression.md
Example for lossless image compression contains a single `\` character as path separator which is an escape character in C#. Double backslash `\\` should be used instead.
Before:
```cs
var snakewareLogo = new FileInfo("c:\path\to\Snakeware.jpg");
```
After:
```cs
var snakewareLogo = new FileInfo("c:\\path\\to\\Snakeware.jpg");
```
> Added double backslashes inside file name

- src/Magick.NET.AvaloniaMediaImaging/IMagickImageExtentions.cs
> Change DPI to 96
